# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImportEnum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ImportEnum.proto*0\n\nImportEnum\x12\n\n\x06\x45NUM_D\x10\x00\x12\n\n\x06\x45NUM_E\x10\x01\x12\n\n\x06\x45NUM_F\x10\x02\x62\x06proto3')

_IMPORTENUM = DESCRIPTOR.enum_types_by_name['ImportEnum']
ImportEnum = enum_type_wrapper.EnumTypeWrapper(_IMPORTENUM)
ENUM_D = 0
ENUM_E = 1
ENUM_F = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMPORTENUM._serialized_start=20
  _IMPORTENUM._serialized_end=68
# @@protoc_insertion_point(module_scope)
